### ISSUE TITLE
R version too strict?

### ISSUE THREAD

**Issue by tacman** [survos/platform-recipes#2]
Do we really need 3.2.2? 

```

ERROR: this R is version 3.1.2, package 'survos' requires R >= 3.2.2
Error: Command failed (1)
```

If so, how do I upgrade, this is the version I recently downloaded.

**Comment by phillc73** [comment]
No good reason. It's just the version I currently have on my machine. I'll bump it back a few versions. 

How about I base it on what's currently available from Debian Stable? That should be far enough back that almost everyone will have it, and not too far back that things won't work.

**Comment by phillc73** [comment]
Next release of package will only require R >= 3.1.1

This version of R is packaged with Debian Jessie and Ubuntu 14.10, so hopefully will be fine for most users.

https://packages.debian.org/jessie/r-base
https://launchpad.net/ubuntu/utopic/+package/r-base-dev
